# name: build docs
# on:
#   push:
#     branches:
#       - master
#       - main
# jobs:
#   deploy:
#     runs-on: ubuntu-latest
#     steps:
#       - uses: actions/checkout@v2
#       - uses: actions/setup-python@v2
#         with:
#           python-version: 3.8
#       - run: pip install \
#              mkdocs-material \
#              mkdocs-awesome-pages-plugin \
#              mkdocs-video
#       - run: mkdocs gh-deploy --force

# jobs:
#   build:
#     runs-on: ubuntu-latest

#     steps:
#       - name: ðŸ›Žï¸ Checkout code
#         uses: actions/checkout@v4

#       - name: ðŸ“¦ Setup Node.js
#         uses: actions/setup-node@v4
#         with:
#           node-version: '22'

#       - name: ðŸ“¥ Install dependencies
#         run: npm install

#       - name: ðŸ—ï¸ Build
#         run: npm run build

#       - name: ðŸš€Deploy to GitHub PagesðŸš€  // --> this deploys to gh-pages
#         if: github.ref == 'refs/heads/main'
#         uses: peaceiris/actions-gh-pages@v3
#         with:
#           github_token: ${{ secrets.GITHUB_TOKEN }}
#           publish_dir: ./dist
